# Generated by Django 4.2.5 on 2023-09-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('aadhar_card', models.CharField(max_length=16)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('previous_school', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('caste', models.CharField(max_length=50)),
                ('admission_class', models.CharField(max_length=50)),
                ('admission_date', models.DateField()),
            ],
        ),
    ]
