# Generated by Django 4.2.5 on 2023-09-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='mobile_number',
            field=models.CharField(default=9108890864, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
