# Generated by Django 4.2.5 on 2023-10-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admission_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='previous_school',
            field=models.CharField(max_length=2000),
        ),
    ]
