# Generated by Django 4.2.5 on 2023-10-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_admission_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='previous_school',
            field=models.TextField(),
        ),
    ]
