# Generated by Django 4.2.5 on 2023-09-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('admission_date', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=1000)),
                ('photo', models.CharField(max_length=1000)),
                ('aadhar_card_number', models.CharField(max_length=12, unique=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('previous_school_details', models.TextField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
            ],
        ),
    ]
