# Generated by Django 4.2.5 on 2023-09-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='address',
            field=models.TextField(max_length=1000),
        ),
    ]
