# Generated by Django 4.2.7 on 2023-11-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0007_admission_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exam_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sports_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('miscellaneous_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateField()),
                ('fee_for_month', models.CharField(max_length=255)),
                ('receipt_number', models.CharField(max_length=20)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admission')),
            ],
        ),
    ]
