# Generated by Django 4.2.5 on 2023-09-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='month',
            field=models.CharField(default=7, max_length=255),
            preserve_default=False,
        ),
    ]
